<?php

namespace ContactBoxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRepository extends EntityRepository
{

    public function selectGroups(User $user) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT g FROM ContactBoxBundle:Groups g WHERE g.userOwner = :user'
        );
        $query->setParameter('user', $user);
        return $query->getResult();
    }
}
