<?php

namespace ContactBoxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    public function searchByFirstName($name) {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT people FROM ContactBoxBundle:Person people WHERE people.firstName LIKE :name');
        $query->setParameter('name', $name);

        return $query->getResult();
    }

    public function searchByLastName($lastName) {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT people FROM ContactBoxBundle:Person people WHERE people.lastName LIKE :lastName');
        $query->setParameter('lastName', $lastName);

        return $query->getResult();
    }

    public function findOrderedByLastName() {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT people FROM ContactBoxBundle:Person people ORDER BY people.lastName ASC'
        );
        return $query->getResult();
    }

    public function findByUser(User $user) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT p FROM ContactBoxBundle:Person p JOIN p.users t WHERE t = :user'
        );
        $query->setParameter('user', $user);
        return $query->getResult();
    }




}
